### PR TITLE
Detectivewallhack

### PR DESCRIPTION
**Pull request by Bobakanoosh**

### CODE REVIEW

**Comment by Bara20** [comment]
I think that wasn't requested by @Nachtfrische

**Comment by Bobakanoosh** [comment]
I'm confused -- it was requested by him, are you waiting for him to look over it?

**Comment by Nachtfrische** [comment]
I'm confused as well, what is this commit doing @Bobakanoosh ?

**Comment by Bobakanoosh** [comment]
@Nachtfrische #160

**Comment by Bobakanoosh** [comment]
Sorry for all the taser.inc and taser.sp files, for some reason they keep following along with each new branch I make, even though those are fully merged.

**Comment by Nachtfrische** [comment]
@Bobakanoosh I requested that when you are the detective and you buy the wallhack, you can see all the players through the walls. But the color of the other players is white so you won't know if the person is innocent or a traitor.

**Comment by Bobakanoosh** [comment]
@Nachtfrische d0598ce

**Comment by Bobakanoosh** [comment]
Ahhh wait I am very very stupid

**Comment by Bara20** [comment]
To solve the commits issue, try to refork this repo.

**Comment by Bara20** [comment]
And create a new branch for new pull requests.

**Pull request closed without merging**
