### PR TITLE
Version 2.3

### PR DESCRIPTION
**Pull request by Bara20**
**Don't try it, if you don't know what you do.**
---
***Changelogs:***
- New configs ( #168 )
- Add round slays (incl. natives and admin command) ( #155 )
- Add version convar to each plugin
- Add Parachute as shop item ( #198 )
- Add discount prices to shop ( #207 )
- Updated plugin tag
- Block grab of doors and buttons ( #200 )
- Move SetrandomSeed to OnPluginStart
- Usage of userid's instead of client index's for ragdoll array
- Fix sprint plugin ( #199 )
- Fix a "bug" with sql on connect forward
- Fix a bug with negative karma and bad karma ban ( #201 )
- Fix several typos
- Fix Icons
- Fix wallhack ( #211 )
--- 
With merge we close this issue(s): #186 #153

### CODE REVIEW

**Comment by Bara20** [comment]
It's not done. I'll mention you if it's done.

**Comment by good-live** [comment]
broleAgain is a left over from the old team selection code. (Can be deleted)

**Comment by Bara20** [comment]
Configs are finally done... now... let's add some new features and fixing bugs

**Comment by Bara20** [comment]
> Search "CreateConVar" (474 hits in 39 files)

and only configs...

> Search "AutoExecConfig_CreateConVar" (431 hits in 32 files)

**Comment by Bara20** [comment]
I think that's enough for this pull request. I'v attached a zip file with compiled plugins for testing.
[plugins.zip](https://github.com/Bara20/TroubleinTerroristTown/files/1465315/plugins.zip)

@good-live

**Comment by Bara20** [comment]
I've cleanup (some commits merged) this pull request a bit.
Here are the latest compiled versions: [plugins.zip](https://github.com/Bara20/TroubleinTerroristTown/files/1468347/plugins.zip)

**Comment by Bara20** [comment]
[plugins.zip](https://github.com/Bara20/TroubleinTerroristTown/files/1468671/plugins.zip)

**Pull request merged**
