### PR TITLE
Merge current master into stable

### PR DESCRIPTION
**Pull request by Bara20**

### CODE REVIEW

**Comment by good-live** [comment]
I think this would need a lot more testing before we should mark it as stable.
However the only bug that i know (we aren't using all of the features) is that there is sometime a Freeze of ~3-5 sec when initiating a round (choosing roles) @kikoplg Are there any more?

**Comment by kikoplg** [comment]
High CPU usage and lag/freeze at rolechoosing

**Comment by popey456963** [comment]
Any updates on the freeze at the start of the round?  Confusing me because the delay seems to increase exponentially with number of players, which seems weird when you are surely literally just picking a random number and giving it to people?  Is there anything else you do at round start?

**Comment by good-live** [comment]
I haven't got the time to take a look at it, but it's around 200 lines of code with some loops in it.

**Comment by popey456963** [comment]
@good-live If you point me to the lines, I've got moderately decent at sourcepawn, I can take a look at it.

**Comment by good-live** [comment]
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt.sp#L609

**Comment by popey456963** [comment]
Realised very quickly I was out of my depth, nowhere near as proficient enough in Sourcepawn to do anything like this.  I will however leave the code I did write to try to solve this below:

```
// Assumes we have an array called aPlayers which contains all the players
// Also assumes roles[64] defaults to a 64 length array and none of TTT_TEAM_* are 0
float roles[64];
int TCount = GetTCount(aPlayers.Length);
int DCount = GetDCount(aPlayers.Length);

// Remember past role of this player
LoopValidClients(i) {
	g_iLastRole[client] = g_iRole[aPlayers.Get(i)]
}

// Assign all ranks to be given out to an array
for (int i = 0; i < players; i++) {
	if (TCount > 0) { TCount--; roles[i] = TTT_TEAM_TRAITOR; continue }
	if (DCount > 0) { DCount--; roles[i] = TTT_TEAM_DETECTIVE; continue }
	roles[i] = TTT_TEAM_INNOCENT;
}

// We want an array that looks like [0,0,1,3,2,0,2,3,...]
// https://sm.alliedmods.net/new-api/sorting/__raw
roles = SortFloats(roles, sizeof(roles), Sort_Random);

// We now need to assign roles to each of the players from this array
int n = 0;

for (int i = 0; i < sizeof(roles); i++) {
	if (roles[i] == 0) { continue; }
	// AssignRole takes a client and a role, and assigns the role to the client.
	g_iRole[aPlayers[n]] = roles[i];
	n++;
}
```

You'll see I've approached the challenge differently, aiming to create an array of positions that I randomise instead of randomising each individuals position.  I hypothesised that the only likely cause of lag here was generating all the random numbers.  Sorry I couldn't be of more help, guess I've just gotta keep on learning.

**Comment by good-live** [comment]
I've just pushed a small fix. Would be nice if some of you could test it with a few more players. (Theres still always the chance of an nearly endless loop, but its very very very unlikely.)

**Pull request closed without merging**
